import glob
import json
import os
import sys

from pypdf import PdfReader, PdfWriter
from pypdf.annotations import FreeText


# Minimum font size we will shrink to before we stop shrinking and wrap only.
MIN_FONT_SIZE = 6.0
# Average glyph-width-to-font-size ratio used to estimate rendered text width without
# needing the actual font metrics (FreeText appearance is generated by the viewer).
# CJK glyphs are ~full-em wide; Latin averages ~0.5em. We pick per-string below.
_LATIN_WIDTH_RATIO = 0.52
_CJK_WIDTH_RATIO = 1.0
# Line height as a multiple of font size.
_LINE_HEIGHT_RATIO = 1.2


def _has_cjk(text):
    """True if the string contains any CJK (or other wide non-Latin) character."""
    for ch in text:
        o = ord(ch)
        if (
            0x2E80 <= o <= 0x9FFF      # CJK radicals, Kangxi, CJK Unified
            or 0x3000 <= o <= 0x303F   # CJK symbols/punctuation
            or 0x3040 <= o <= 0x30FF   # Hiragana + Katakana
            or 0xAC00 <= o <= 0xD7AF   # Hangul syllables
            or 0xF900 <= o <= 0xFAFF   # CJK compatibility ideographs
            or 0xFF00 <= o <= 0xFFEF   # full-width forms
            or 0x20000 <= o <= 0x2FA1F # CJK extension B+
        ):
            return True
    return False


def _resolve_cjk_font():
    """Return a usable CJK font file path, or None. FAIL OPEN — never raises.

    Checks, in order: LILY_CJK_FONT_PATH env var; common macOS/Windows/Linux system
    fonts; and the repo's bundled runtime LibreOffice fonts dir if discoverable.
    """
    candidates = []
    env = os.environ.get("LILY_CJK_FONT_PATH")
    if env:
        candidates.append(env)

    # macOS
    candidates += [
        "/System/Library/Fonts/PingFang.ttc",
        "/System/Library/Fonts/Hiragino Sans GB.ttc",
    ]
    # Windows
    candidates += [
        "C:\\Windows\\Fonts\\msyh.ttc",
        "C:\\Windows\\Fonts\\simsun.ttc",
    ]
    # Linux system Noto CJK
    try:
        candidates += glob.glob(
            "/usr/share/fonts/**/NotoSansCJK*", recursive=True
        )
    except Exception:
        pass

    # Repo-bundled runtime LibreOffice fonts, if this script lives inside the repo tree.
    try:
        here = os.path.dirname(os.path.abspath(__file__))
        root = here
        for _ in range(8):  # walk up looking for a plausible repo root
            parent = os.path.dirname(root)
            if parent == root:
                break
            root = parent
            for pat in (
                os.path.join(root, "**", "libreoffice", "**", "fonts", "**", "*.ttc"),
                os.path.join(root, "**", "libreoffice", "**", "fonts", "**", "*.ttf"),
                os.path.join(root, "**", "libreoffice", "**", "fonts", "**", "*.otf"),
            ):
                try:
                    candidates += glob.glob(pat, recursive=True)
                except Exception:
                    pass
    except Exception:
        pass

    for path in candidates:
        try:
            if path and os.path.isfile(path):
                return path
        except Exception:
            continue
    return None


def _estimate_line_width(text, font_size):
    """Rough rendered width of a single line at font_size (points)."""
    width = 0.0
    for ch in text:
        o = ord(ch)
        ratio = _CJK_WIDTH_RATIO if (
            0x2E80 <= o <= 0x9FFF or 0x3000 <= o <= 0x30FF
            or 0xAC00 <= o <= 0xD7AF or 0xF900 <= o <= 0xFAFF
            or 0xFF00 <= o <= 0xFFEF
        ) else _LATIN_WIDTH_RATIO
        width += ratio * font_size
    return width


def _wrap_text(text, font_size, max_width):
    """Greedy-wrap text to fit max_width; returns list of lines. Never drops content."""
    if max_width <= 0:
        return text.splitlines() or [text]
    lines = []
    for para in text.split("\n"):
        if not para:
            lines.append("")
            continue
        # Split on spaces where present (Latin); fall back to per-char (CJK has no spaces).
        tokens = para.split(" ") if " " in para else list(para)
        joiner = " " if " " in para else ""
        cur = ""
        for tok in tokens:
            trial = tok if not cur else (cur + joiner + tok)
            if _estimate_line_width(trial, font_size) <= max_width or not cur:
                cur = trial
            else:
                lines.append(cur)
                cur = tok
        if cur or not lines:
            lines.append(cur)
    return lines


def _fit_text_to_rect(text, rect, base_font_size):
    """Shrink font size and wrap so text fits rect. FAIL OPEN.

    Returns (fitted_text, fitted_font_size). If it cannot make things better,
    returns the original text with the smallest attempted size (>= MIN_FONT_SIZE),
    never worse than the input.
    """
    try:
        left, bottom, right, top = rect
        rect_w = abs(float(right) - float(left))
        rect_h = abs(float(top) - float(bottom))
    except Exception:
        return text, base_font_size
    if rect_w <= 0 or rect_h <= 0:
        return text, base_font_size

    size = float(base_font_size)
    best_lines = [text]
    while size >= MIN_FONT_SIZE:
        lines = _wrap_text(text, size, rect_w)
        needed_h = len(lines) * size * _LINE_HEIGHT_RATIO
        widest = max((_estimate_line_width(ln, size) for ln in lines), default=0.0)
        if needed_h <= rect_h and widest <= rect_w:
            return "\n".join(lines), size
        best_lines = lines
        size -= 1.0
    # Could not fully fit even at MIN_FONT_SIZE: use min size + wrapped text.
    # Still strictly better than an unwrapped oversized single line.
    return "\n".join(best_lines), MIN_FONT_SIZE


def transform_from_image_coords(bbox, image_width, image_height, pdf_width, pdf_height):
    x_scale = pdf_width / image_width
    y_scale = pdf_height / image_height

    left = bbox[0] * x_scale
    right = bbox[2] * x_scale

    top = pdf_height - (bbox[1] * y_scale)
    bottom = pdf_height - (bbox[3] * y_scale)

    return left, bottom, right, top


def transform_from_pdf_coords(bbox, pdf_height):
    left = bbox[0]
    right = bbox[2]

    pypdf_top = pdf_height - bbox[1]      
    pypdf_bottom = pdf_height - bbox[3]   

    return left, pypdf_bottom, right, pypdf_top


def fill_pdf_form(input_pdf_path, fields_json_path, output_pdf_path):
    
    with open(fields_json_path, "r") as f:
        fields_data = json.load(f)
    
    reader = PdfReader(input_pdf_path)
    writer = PdfWriter()
    
    writer.append(reader)
    
    pdf_dimensions = {}
    for i, page in enumerate(reader.pages):
        mediabox = page.mediabox
        pdf_dimensions[i + 1] = [mediabox.width, mediabox.height]
    
    cjk_font_path = _resolve_cjk_font()

    annotations = []
    for field in fields_data["form_fields"]:
        page_num = field["page_number"]

        page_info = next(p for p in fields_data["pages"] if p["page_number"] == page_num)
        pdf_width, pdf_height = pdf_dimensions[page_num]

        if "pdf_width" in page_info:
            transformed_entry_box = transform_from_pdf_coords(
                field["entry_bounding_box"],
                float(pdf_height)
            )
        else:
            image_width = page_info["image_width"]
            image_height = page_info["image_height"]
            transformed_entry_box = transform_from_image_coords(
                field["entry_bounding_box"],
                image_width, image_height,
                float(pdf_width), float(pdf_height)
            )
        
        if "entry_text" not in field or "text" not in field["entry_text"]:
            continue
        entry_text = field["entry_text"]
        text = entry_text["text"]
        if not text:
            continue
        
        try:
            base_font_size = float(entry_text.get("font_size", 14))
        except (TypeError, ValueError):
            base_font_size = 14.0
        font_color = entry_text.get("font_color", "000000")

        # Default the font to a CJK-capable face when the text contains CJK and one is
        # available; otherwise keep the caller's font (or "Arial"). Fail open.
        if _has_cjk(text) and cjk_font_path:
            # FreeText's `font` is a name string; use the resolved family name if the
            # caller didn't already specify one. This keeps ASCII-only fills untouched.
            font_name = entry_text.get("font") or os.path.splitext(
                os.path.basename(cjk_font_path)
            )[0]
        else:
            font_name = entry_text.get("font", "Arial")

        # Shrink and/or wrap the text so it fits its rectangle (prevents overrun/遮挡).
        # ASCII text that already fits is returned unchanged at its original size.
        fitted_text, fitted_size = _fit_text_to_rect(
            text, transformed_entry_box, base_font_size
        )
        # Preserve integer formatting (e.g. "14pt") when the size is whole, matching
        # the prior output for text that already fits.
        if float(fitted_size).is_integer():
            font_size = str(int(fitted_size)) + "pt"
        else:
            font_size = str(fitted_size) + "pt"

        annotation = FreeText(
            text=fitted_text,
            rect=transformed_entry_box,
            font=font_name,
            font_size=font_size,
            font_color=font_color,
            border_color=None,
            background_color=None,
        )
        annotations.append(annotation)
        writer.add_annotation(page_number=page_num - 1, annotation=annotation)
        
    with open(output_pdf_path, "wb") as output:
        writer.write(output)
    
    print(f"Successfully filled PDF form and saved to {output_pdf_path}")
    print(f"Added {len(annotations)} text annotations")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: fill_pdf_form_with_annotations.py [input pdf] [fields.json] [output pdf]")
        sys.exit(1)
    input_pdf = sys.argv[1]
    fields_json = sys.argv[2]
    output_pdf = sys.argv[3]
    
    fill_pdf_form(input_pdf, fields_json, output_pdf)
