"use strict";

const CHARACTER_SCHEMA_VERSION = 1;
const CHARACTER_BINDING_SCHEMA_VERSION = 1;
const CHARACTER_COMPATIBILITY_PROFILE_VERSION = 1;
const CHARACTER_COMPATIBILITY_PROFILE = "lily-character-worlds-v1";
const CHARACTER_ASSET_LIMITS_VERSION = 1;

const MAX_CHARACTER_CANONICAL_BYTES = 8 * 1024 * 1024;
const MAX_CHARACTER_SOURCE_BYTES = 32 * 1024 * 1024;
const MAX_CHARACTER_TEXT_FIELD_BYTES = 1024 * 1024;
const MAX_CHARACTER_ASSET_COUNT = 1000;
const MAX_CHARACTER_ASSET_BYTES = 32 * 1024 * 1024;
const MAX_CHARACTER_ASSET_TOTAL_BYTES = 128 * 1024 * 1024;
const MAX_CHARACTER_ASSET_PURPOSE_BYTES = 256;
const MAX_CHARACTER_ASSET_MIME_BYTES = 255;
const MAX_CHARACTER_BINDING_BYTES = 64 * 1024;
const MAX_CHARACTER_RECONCILE_FILES = 1000;
const MAX_CHARACTER_RECONCILE_FILE_BYTES = 128 * 1024 * 1024;
const DEFAULT_CHARACTER_ORPHAN_GRACE_MS = 24 * 60 * 60 * 1000;
const CHARACTER_BLOB_RECONCILE_CURSOR_KEY = "character_worlds.blob_reconcile_cursor.v1";

module.exports = {
  CHARACTER_SCHEMA_VERSION,
  CHARACTER_BINDING_SCHEMA_VERSION,
  CHARACTER_COMPATIBILITY_PROFILE_VERSION,
  CHARACTER_COMPATIBILITY_PROFILE,
  CHARACTER_ASSET_LIMITS_VERSION,
  MAX_CHARACTER_CANONICAL_BYTES,
  MAX_CHARACTER_SOURCE_BYTES,
  MAX_CHARACTER_TEXT_FIELD_BYTES,
  MAX_CHARACTER_ASSET_COUNT,
  MAX_CHARACTER_ASSET_BYTES,
  MAX_CHARACTER_ASSET_TOTAL_BYTES,
  MAX_CHARACTER_ASSET_PURPOSE_BYTES,
  MAX_CHARACTER_ASSET_MIME_BYTES,
  MAX_CHARACTER_BINDING_BYTES,
  MAX_CHARACTER_RECONCILE_FILES,
  MAX_CHARACTER_RECONCILE_FILE_BYTES,
  DEFAULT_CHARACTER_ORPHAN_GRACE_MS,
  CHARACTER_BLOB_RECONCILE_CURSOR_KEY,
};
